spring:
  application:
    name: cellar-backend-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_cellar
    username: postgres
    password: 1234

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized  # в проде — when-authorized, для отладки — always

jwt:
  secret: your-256-bit-secret-key-for-jwt-token-generation-minimum-32-characters-long
  access-expiration: 900000   # 15 минут (access token)
  refresh-expiration: 604800000 # 7 дней (refresh token, для хранения в БД)



